apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense #name of the cluster
  region: us-east-1

managedNodeGroups:
- name: expense
  instanceType: m5.large #instance type 
  desiredCapacity: 3 #3 nodes we are mentioning
  spot: true #all should be spot instances